# This file was generated by roxyPackage::roxy.package()
# and will likely be overwritten on its next run.
# Editing is futile.

#' \packageDescription{koRpus}
#'
#' The DESCRIPTION file:
#' \tabular{ll}{
#' Package: \tab koRpus\cr
#' Type: \tab Package\cr
#' Version: \tab 0.13-9\cr
#' Date: \tab 2023-04-19\cr
#' Depends: \tab R (>= 3.0.0),sylly (>= 0.1-7)\cr
#' Enhances: \tab rkward\cr
#' Encoding: \tab UTF-8\cr
#' License: \tab GPL (>= 3)\cr
#' LazyLoad: \tab yes\cr
#' URL: \tab https://reaktanz.de/?c=hacking&s=koRpus\cr
#' }
#'
#' @title
#' \packageTitle{koRpus}
#' @author
#' \packageAuthor{koRpus}
#'
#' Maintainer: \packageMaintainer{koRpus}
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL